# Generated by Django 5.1.4 on 2025-01-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_product_price', 'Can change product price')]},
        ),
    ]
